import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useContext, useState } from 'react'
import userContext from '../context/user/userContext'
import baseUrl from '../database/baseUrl'
import styles from '../styles/Home.module.css'

export default function FreeCourse({ post }) {
  const context = useContext(userContext)
  const { mode, user, setSearchkey, searchkey } = context
  // console.log(answer.length)

  return (
    <div className=" ">

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' mt-[-2em] py-44 mb-24  '  >
        {!user && <>
          <div className=" flex justify-center mb-5">
            <img className='' src='https://cdn-icons-png.flaticon.com/128/9356/9356674.png' />

          </div>
          <h1 className=' text-3xl md:text-3xl mb-80 text-center font-sans' style={{ color: mode === 'dark' ? 'white' : '' }}>Please Login To See The Document</h1>
        </>}
        {user &&


          <section className="text-gray-600 body-font">

            <div className="container px-5 -mt-10  mx-auto">
              <div className="flex flex-wrap w-full mb-20 flex-col items-center text-center">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-2 "
                  style={{ color: mode === 'dark' ? 'white' : '' }}
                >All Documentation</h1>
                <p className="lg:w-1/2 w-full leading-relaxed text-gray-500">Whatever cardigan tote bag tumblr hexagon brooklyn asymmetrical gentrify, subway tile poke farm-to-table.</p>
              </div>

              {/* <div className=''>
                {searchkey ? (<h1 className=' text-center text-3xl'>Not Found</h1>)
                  :
                  <div className=' flex flex-wrap -m-4 '>
                    {
                      post.filter((obj) => obj.title.toLowerCase().includes(searchkey)).map((item) => {
                        return (
                          <div className="xl:w-1/4 md:w-1/2 p-10 py-1 md:p-4 mb-2  " key={item._id} >
                            <Link href={`/answers/${item._id}`}>
                              <div className="p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1 " style={{
                                border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                              }}>
                                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4">
                                  <img src={item.logo} alt="reactjs" />
                                </div>
                                <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>{item.title}</h2>
                                <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>{item.description}</p>
                              </div>
                            </Link>
                          </div>
                        )
                      })
                    }
                  </div>}
              </div> */}


              {/* <div className="flex flex-wrap -m-4">
                <div >
                  {
                    post.filter((obj) => obj.title.toLowerCase().includes(searchkey)).map((item) => {
                      return (
                        <div className="  flex flex-wrap -m-4">
                          <div className="xl:w-1/4 md:w-1/2 p-10 py-1 md:p-4 mb-2  " key={item._id} >
                            <Link href={`/answers/${item._id}`}>
                              <div className="p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1 " style={{
                                border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                              }}>
                                <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4">
                                  <img src={item.logo} alt="reactjs" />
                                </div>
                                <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>{item.title}</h2>
                                <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>{item.description}</p>
                              </div>
                            </Link>
                          </div>
                        </div>

                      )
                    })
                  }
                  <Link href={'/docs/reactjs'}>
                    <div className="p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1 " style={{
                      border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                    }}>
                      <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4">
                        <img src="img/react.png" alt="reactjs" />
                      </div>
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>React Js</h2>
                      <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>A JavaScript library for building user interfaces</p>
                    </div>
                  </Link>
                </div>
              </div> */}

              {searchkey ? (<h1 className=' text-center text-3xl'>Not Found</h1>) : <>
                <div className="flex flex-wrap -m-4">
                  {/* { post.filter((obj) => obj.title.toLowerCase().includes(searchkey)).map((item) =>)} */}
                  {post.filter((obj) => obj.title.toLowerCase().includes(searchkey)).map((item) => {
                    return (
                      <div className="xl:w-1/3 md:w-1/2 p-4  ">
                        <Link href={`/answers/${item._id}`}>
                          <div className="p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1 " style={{
                            border: mode === 'dark' ? '2px solid #61DAFB' : ' 2px solid  #e6e3e3',

                          }}>
                            <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4">
                              <img className=' rounded-full' src={item.logo} alt="reactjs" />
                            </div>
                            <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>{item.title}</h2>
                            <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>{item.description}</p>
                          </div>
                        </Link>
                      </div>
                    )
                  })}


                </div>
              </>}

              {/* <div className="flex flex-wrap -m-4">

                <div className="xl:w-1/3 md:w-1/2 p-4 ">
                  <Link href={'/docs/reactjs'}>
                    <div className="p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1 " style={{
                      border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                    }}>
                      <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4">
                        <img src="img/react.png" alt="reactjs" />
                      </div>
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>React Js</h2>
                      <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>A JavaScript library for building user interfaces</p>
                    </div>
                  </Link>
                </div>

                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full -500 mb-4">
                      <img src={mode == 'dark' ? 'img/n.png' : 'img/next.png'} alt="nextjs" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Next Js</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>The React Framework for the Web
                      Used by some of the world's largest companies</p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <Link href={'https://emphasized-carob-aba.notion.site/Electron-Js-0587e05b19914753aea9c276302dc6b6'}>
                    <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                      border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                    }}>
                      <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
                        <img src="https://www.electronjs.org/assets/img/logo.svg" alt="electronjs" />
                      </div>
                      <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Electron Js</h2>
                      <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>Build cross-platform desktop apps with JavaScript, HTML, and CSS</p>
                    </div>
                  </Link>

                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4">
                      <img className='' src="img/javascript.png" alt="javascript" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>JavaScript</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>JavaScript is the world's most popular programming language.
                    </p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4">
                      <img className=' rounded-full' src="img/html.png" alt="html" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Html</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>HTML is the standard markup language for Web pages.
                    </p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4">
                      <img className=' rounded-full' src="img/css.png" alt="css" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Css</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>CSS is the language we use to style an HTML document.
                    </p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4 ">
                  <div className="p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full  mb-4">
                      <img src="img/react.png" alt="reactjs" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>React Js</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>A JavaScript library for building user interfaces</p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full -500 mb-4">
                      <img src={mode == 'dark' ? 'img/n.png' : 'img/next.png'} alt="nextjs" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Next Js</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>The React Framework for the Web
                      Used by some of the world's largest companies</p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 mb-4">
                      <img src="https://www.electronjs.org/assets/img/logo.svg" alt="electronjs" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Electron Js</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>Build cross-platform desktop apps with JavaScript, HTML, and CSS</p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4">
                      <img className='' src="img/javascript.png" alt="javascript" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>JavaScript</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>JavaScript is the world's most popular programming language.
                    </p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4">
                      <img className=' rounded-full' src="img/html.png" alt="html" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Html</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>HTML is the standard markup language for Web pages.
                    </p>
                  </div>
                </div>
                <div className="xl:w-1/3 md:w-1/2 p-4">
                  <div className=" p-6 rounded-xl hover:shadow-2xl hover:shadow-[#6366F1] hover:ring-offset-1 hover:ring-1" style={{
                    border: mode === 'dark' ? '1px solid #61DAFB' : ' 1px solid  #e6e3e3'
                  }}>
                    <div className="w-10 h-10 inline-flex items-center justify-center rounded-full mb-4">
                      <img className=' rounded-full' src="img/css.png" alt="css" />
                    </div>
                    <h2 className="text-lg text-gray-900 font-medium title-font mb-2" style={{ color: mode === 'dark' ? 'white' : '' }}>Css</h2>
                    <p className="leading-relaxed text-base" style={{ color: mode === 'dark' ? 'white' : '' }}>CSS is the language we use to style an HTML document.
                    </p>
                  </div>
                </div>
              </div> */}


            </div>
          </section>}
      </main>
    </div>
  )
}

export async function getServerSideProps() {
  const res = await fetch(`${baseUrl}/api/answer`);
  const post = await res.json()
  // console.log(answer)
  return {
    props: { post }, // will be passed to the page component as props
  }
}